### ISSUE TITLE
Maven usage is incomplete

### ISSUE THREAD

**Issue by Riduidel** [skinny85/jilt#25]
To have jilt working in a maven build, one doesn't only need to have the dependency.

Needed steps are:

* Adding the dependency to the maven pom (documented)
* Adding the annotation processor configuration to maven compiler (not documented)
* Adding the generated code to maven source path using build-helper-maven-plugin (not documented)

Do you want someone to update the readme?

**Comment by skinny85** [comment]
Hi @Riduidel,

thanks a lot for opening the issue!

Here is an example Maven project that I've used to reproduce a bug with Jilt: https://github.com/skinny85/jilt-nullable-problem-repro

It builds for me with Java 8 with `./mvn clean package`, and the only `pom.xml` does is set the compiler source and target to `1.8`, and add some dependencies (including Jilt). It doesn't need any changes to the compiler plugin, or adding the generated director to the source path.

Curious why do you need that other stuff? Could it be that it differs with the Maven and/or Java version that is used?

Thanks,
Adam

**Comment by skinny85** [comment]
I'm closing this one due to inactivity. If you still need anything related to this issue, please comment, and I'll be happy to re-open.

**Comment by Riduidel** [comment]
Sorry to never have answered. I'm currently building a maven project using Java 21, and the test compilation fails because I use Jilt builders in tests, and they're not in the test classpath.

**Comment by skinny85** [comment]
No worries @Riduidel. Would you mind pushing an example repo that exhibits this problem to GitHub, and sharing it here? I have this repo: https://github.com/skinny85/jilt-null-away-example, in which the Builder classes _can_ be used in tests, so I'm curious what the difference is between that one, and your setup.
